export interface Insight {
  slug: string;
  title: string;
  lede: string;
  tags: string[];
  sources: string[];
  updated: string;
}

export const INSIGHTS: Insight[] = [
  {
    slug: "temp-vs-price",
    title: "気温 × 電力価格：東京 15 年史",
    lede: "JMA 日平均気温と JEPX 東京エリア卸電力価格の 15 年相関",
    tags: ["電力", "気象", "東京"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-02",
  },
  {
    slug: "temp-min-hokkaido-vs-price",
    title: "札幌最低気温 × 北海道 JEPX：冬の暖房需要 15 年",
    lede: "寒さが厳しいほど電気代が上がる構造。北本連系線の制約と暖房需要の関係",
    tags: ["電力", "気象", "北海道"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-max-kyushu-vs-price",
    title: "福岡最高気温 × 九州 JEPX：太陽光と冷房需要の綱引き",
    lede: "太陽光発電大国・九州ならではの「夏の昼に価格が下がり、夜に上がる」非対称性",
    tags: ["電力", "気象", "九州", "太陽光"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-max-tokyo-summer",
    title: "東京最高気温 × 東京 JEPX：夏期 6-9 月の絶対偏差相関",
    lede: "25℃ から離れるほど価格が上がる U 字型構造を絶対偏差相関で可視化",
    tags: ["電力", "気象", "東京", "夏期"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-tohoku",
    title: "仙台日平均気温 × 東北 JEPX：火力依存エリアの夏冬両期需要",
    lede: "原発停止後の火力依存と、夏冬両期型需要が価格に響く構造",
    tags: ["電力", "気象", "東北", "原発"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-chubu",
    title: "名古屋日平均気温 × 中部 JEPX：製造業の電力需要パターン",
    lede: "トヨタ・自動車部品など製造業集積エリアの「平日 vs 休日」需要パターン",
    tags: ["電力", "気象", "中部", "製造業"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-kansai",
    title: "大阪日平均気温 × 関西 JEPX：原発再稼働と気温感応度の変化",
    lede: "高浜・大飯・美浜 7 基稼働でベースロード復活、気温感応度が 3 段階に変化",
    tags: ["電力", "気象", "関西", "原発"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-chugoku",
    title: "広島日平均気温 × 中国 JEPX：太陽光大規模導入エリアの昼間反転",
    lede: "国内 2 位の太陽光導入比率 + 島根 2 号機 2024 年再稼働の構造変化",
    tags: ["電力", "気象", "中国", "太陽光", "原発"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-shikoku",
    title: "高松日平均気温 × 四国 JEPX：小規模市場と原発再稼働",
    lede: "国内最小級市場、伊方 3 号機の運転 / 停止が価格に直接反映",
    tags: ["電力", "気象", "四国", "原発"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-hokuriku",
    title: "金沢日平均気温 × 北陸 JEPX：水力ベースロード × 豪雪需要",
    lede: "水力比率国内トップで平時は安定、豪雪期は暖房 + 融雪需要で価格上振れ",
    tags: ["電力", "気象", "北陸", "水力", "豪雪"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "lng-vs-price-tokyo",
    title: "LNG × JEPX 東京：気温では説明できない価格",
    lede: "ドル建て LNG (CIF) × 円建て JEPX 東京の月次相関、ChartDual 2 軸時系列",
    tags: ["電力", "燃料", "東京", "LNG"],
    sources: ["World Bank Pink Sheet", "JEPX スポット市場"],
    updated: "2026-05-05",
  },
  {
    slug: "lng-lag-vs-price-tokyo",
    title: "LNG → JEPX 東京：何ヶ月遅れで価格に効くか",
    lede: "0-12 ヶ月のラグ相関スイープ、ピーク 5-6 ヶ月（長期契約 + 燃料費調整 + 在庫の 3 層）",
    tags: ["電力", "燃料", "東京", "LNG", "ラグ相関"],
    sources: ["World Bank Pink Sheet", "JEPX スポット市場"],
    updated: "2026-05-05",
  },
  {
    slug: "brent-lag-vs-price-tokyo",
    title: "Brent → JEPX 東京：原油は何ヶ月遅れて電力価格に伝播するか",
    lede: "原油 → LNG → JEPX の 2 段伝播、Brent ピークラグ 7-8 ヶ月（LNG より 1-3 ヶ月長い）",
    tags: ["電力", "燃料", "東京", "原油", "ラグ相関"],
    sources: ["World Bank Pink Sheet", "JEPX スポット市場"],
    updated: "2026-05-05",
  },
  {
    slug: "ttf-lag-vs-lng-jp",
    title: "TTF → 日本 LNG CIF：欧州ガス危機は何ヶ月遅れで日本に届くか",
    lede: "ドル建て × ドル建ての純粋燃料伝播、ピーク 3-4 ヶ月（燃料チェーン最上流）",
    tags: ["燃料", "LNG", "TTF", "ラグ相関"],
    sources: ["World Bank Pink Sheet"],
    updated: "2026-05-05",
  },
  {
    slug: "fx-decomp-lng-jepx-tokyo",
    title: "円安 × LNG × JEPX：2022-2023 価格上振れの要因分解",
    lede: "加法 3 要因分解（LNG 要因 + 円安要因 + 相乗効果）、基準月 2020-12 で電気代高騰の正体",
    tags: ["燃料", "為替", "LNG", "東京", "要因分解"],
    sources: ["World Bank Pink Sheet", "日本銀行"],
    updated: "2026-05-05",
  },
  {
    slug: "jgb-vs-yen-lng",
    title: "JGB × LNG：金利と燃料の同時動",
    lede: "10 年物日本国債利回り × LNG の 2 軸時系列、エネルギーと金融の引用インフラ中心軸",
    tags: ["金融", "燃料", "LNG", "JGB"],
    sources: ["World Bank Pink Sheet", "財務省 国債金利"],
    updated: "2026-05-05",
  },
  {
    slug: "precip-hokuriku-vs-price",
    title: "金沢降水量 × 北陸 JEPX：水力ベースロードと豪雪のサイクル",
    lede: "降水量 → ダム水位 → 春の水力出力増 → ベースロード安定の連鎖",
    tags: ["電力", "気象", "北陸", "水力", "降水量"],
    sources: ["JEPX スポット市場", "気象庁 日次降水量"],
    updated: "2026-05-05",
  },
  {
    slug: "precip-kyushu-vs-price",
    title: "福岡降水量 × 九州 JEPX：豪雨年の太陽光出力低下と需要抑制",
    lede: "太陽光大量導入下での降水量、太陽光低下と冷房需要抑制の両方向効果が同時発生",
    tags: ["電力", "気象", "九州", "太陽光", "降水量"],
    sources: ["JEPX スポット市場", "気象庁 日次降水量"],
    updated: "2026-05-06",
  },
  {
    slug: "solar-vs-sunshine-tokyo",
    title: "太陽光発電量 × 東京日照時間：発電ポテンシャルの可視化",
    lede: "全国太陽光発電量 × 東京日照時間の月次相関 +0.70-0.85、再エネのポテンシャル指標",
    tags: ["電力", "気象", "東京", "太陽光", "再エネ"],
    sources: ["METI 電力調査統計", "気象庁 日照時間"],
    updated: "2026-05-06",
  },
  {
    slug: "nuclear-vs-jepx-kansai",
    title: "原子力発電量 × JEPX 関西：再稼働 7 基のベースロード復活",
    lede: "高浜・大飯・美浜 7 基稼働で月次相関 -0.40〜-0.60、本州最安水準を維持",
    tags: ["電力", "原発", "関西", "ベースロード"],
    sources: ["METI 電力調査統計", "JEPX スポット市場"],
    updated: "2026-05-06",
  },
  {
    slug: "renewables-share-trend",
    title: "再エネ比率の 5 年トレンド：エネルギー基本計画 2030 年目標 36-38% への道のり",
    lede: "全国再エネ比率の 5 年月次トレンド、年率 +1.5%pt ペース、2030 年目標到達には加速が必要",
    tags: ["電力", "再エネ", "全国", "エネルギー基本計画"],
    sources: ["METI 電力調査統計", "エネルギー基本計画"],
    updated: "2026-05-06",
  },
  {
    slug: "thermal-vs-lng",
    title: "火力発電量 × LNG：直感的仮説の反証",
    lede: "LNG 高騰時も火力は減らない。火力 = 需要調整役、燃料コストは JEPX 価格に反映される構造",
    tags: ["電力", "燃料", "LNG", "火力"],
    sources: ["METI 電力調査統計", "World Bank Pink Sheet"],
    updated: "2026-05-06",
  },
  {
    slug: "demand-vs-temp",
    title: "販売電力量 × 全国気温：需要側の U 字パターン",
    lede: "需要は快適温度 20-25℃ で最低、絶対偏差で r=+0.65〜+0.75。冬偏重の構造を実証",
    tags: ["電力", "気象", "全国", "需要"],
    sources: ["METI 電力調査統計", "気象庁 日次気温"],
    updated: "2026-05-06",
  },
  {
    slug: "wind-vs-wind-hokkaido",
    title: "風力発電量 × 札幌風速：再エネ × 気象シリーズ 2 本目",
    lede: "全国風力 × 札幌風速、月次相関 r=+0.30〜+0.50（中程度）。地理的偏在で太陽光より弱い相関",
    tags: ["電力", "再エネ", "風力", "北海道"],
    sources: ["METI 電力調査統計", "気象庁 日次風速"],
    updated: "2026-05-06",
  },
  {
    slug: "wind-vs-wind-hokuriku",
    title: "風力発電量 × 金沢風速：日本海側冬季季節風の構造",
    lede: "金沢の冬期 6-8 m/s + 夏期 2-3 m/s の極端な振幅、北海道とは異なる位相",
    tags: ["電力", "再エネ", "風力", "北陸"],
    sources: ["METI 電力調査統計", "気象庁 日次風速"],
    updated: "2026-05-06",
  },
  {
    slug: "solar-sunshine-9-region-heatmap",
    title: "9 地点 × 36 ヶ月 日照時間ヒートマップ：太陽光ポテンシャルの地理性",
    lede: "瀬戸内海（広島・高松）の太陽光最有利 vs 日本海側（札幌・金沢）の不利、地理的格差を可視化",
    tags: ["電力", "再エネ", "太陽光", "ヒートマップ"],
    sources: ["気象庁 日次日照時間"],
    updated: "2026-05-06",
  },
  {
    slug: "wind-9-region-heatmap",
    title: "9 地点 × 36 ヶ月 風速ヒートマップ：陸上風力立地の地理的妥当性",
    lede: "金沢・札幌の冬季季節風が赤、太平洋側 + 内陸が穏やかで青。陸上風力立地集中の根拠（Day 11 で 9 地点完全体に拡張）",
    tags: ["電力", "再エネ", "風力", "ヒートマップ"],
    sources: ["気象庁 日次風速"],
    updated: "2026-05-07",
  },
  {
    slug: "snow-9-region-heatmap",
    title: "9 地点 × 36 ヶ月 積雪ヒートマップ：雪国 vs 太平洋側の極端な格差",
    lede: "札幌 + 金沢のみ赤い帯、他 7 地点はほぼ青。水力ベースロード + 暖房需要の地理的根拠",
    tags: ["電力", "気象", "雪国", "ヒートマップ"],
    sources: ["気象庁 月次最深積雪"],
    updated: "2026-05-06",
  },
  {
    slug: "thermal-fuel-cost-decomp",
    title: "火力 × LNG 燃料コスト要因分解：Phase 2-A delivery の象徴",
    lede: "火力発電量 × LNG ドル建て CIF を加法 3 要因分解。基準月 2021-04 で燃料コスト増の 85-90% は燃料価格要因",
    tags: ["電力", "燃料", "LNG", "火力", "要因分解"],
    sources: ["METI 電力調査統計", "World Bank Pink Sheet"],
    updated: "2026-05-07",
  },
  {
    slug: "precip-9-region-heatmap",
    title: "9 地点 × 36 ヶ月 降水量ヒートマップ：3 つの気象パターンの重ね合わせ",
    lede: "北陸冬季豪雪 + 太平洋側梅雨 + 九州台風の 3 パターンが地理的にモザイク状に重なる構造、再エネ + 需要への 3 経路",
    tags: ["電力", "気象", "降水量", "ヒートマップ"],
    sources: ["気象庁 日次降水量"],
    updated: "2026-05-07",
  },
  {
    slug: "temp-9-region-heatmap",
    title: "9 地点 × 36 ヶ月 平均気温ヒートマップ：年周期と温暖化トレンド",
    lede: "9 地点すべてが年周期で揃う唯一の気象変数、緯度差 14℃ の地理的偏在 + 2023-2025 年の高温 3 連続",
    tags: ["電力", "気象", "気温", "ヒートマップ"],
    sources: ["気象庁 日次気温"],
    updated: "2026-05-07",
  },
  {
    slug: "multi-region-jepx-comparison",
    title: "9 エリア JEPX 比較：地域差の構造と原因",
    lede: "9 エリアの卸電力価格を 1 ページで比較、原発再稼働 / 太陽光導入 / 火力依存 / 水力比率の刻印を可視化",
    tags: ["電力", "全国", "JEPX", "原発", "太陽光"],
    sources: ["JEPX スポット市場"],
    updated: "2026-05-07",
  },
  {
    slug: "region-fuel-sensitivity",
    title: "9 エリア × LNG 価格感応度：原発再稼働状況の刻印",
    lede: "原発再稼働済の関西 + 九州（r=+0.30）vs 火力依存の東京 + 中部（r=+0.65）、電源構成の経済効果を数値化",
    tags: ["電力", "燃料", "LNG", "全国", "原発"],
    sources: ["World Bank Pink Sheet", "JEPX スポット市場"],
    updated: "2026-05-07",
  },
  {
    slug: "spread-us-jp-10y-vs-fx",
    title: "日米 10 年金利差 × USD/JPY：円安要因の本丸",
    lede: "米 10y − 日 10y のスプレッドと USD/JPY の月次相関 r=+0.75-0.85、為替を駆動する金利差の構造",
    tags: ["金融", "金利", "為替", "USD/JPY"],
    sources: ["U.S. Treasury", "財務省 国債金利", "BOJ FM08"],
    updated: "2026-05-07",
  },
  {
    slug: "us-yield-curve-vs-jp-demand",
    title: "米国イールドカーブ × 日本電力需要：景気波及の長いトンネル",
    lede: "米 30y − 米 2y と日本販売電力量、12-18 ヶ月遅延の景気サイクル波及を可視化",
    tags: ["金融", "金利", "電力", "需要", "景気サイクル"],
    sources: ["U.S. Treasury", "METI 電力調査統計"],
    updated: "2026-05-07",
  },
  {
    slug: "us-30y-vs-jgb-30y",
    title: "米 30 年金利 × 日本 30 年 JGB：超長期金利の連動と乖離",
    lede: "Phase 3-B で jgb-30y-yield 着地、超長期金利のグローバル連動 + YCC 期の日本独自性を初めて 1 ページで可視化",
    tags: ["金融", "金利", "超長期", "JGB"],
    sources: ["U.S. Treasury", "財務省 国債金利"],
    updated: "2026-05-07",
  },
  {
    slug: "us-10y-vs-yen-lng",
    title: "米 10 年金利 × 円建て LNG：米金融政策の燃料コストへの影響",
    lede: "米金融政策 → 米金利 → 為替 → 日本の燃料コストの伝播経路、Insight #16 の続編で米国側からの視点",
    tags: ["金融", "金利", "燃料", "LNG", "為替"],
    sources: ["U.S. Treasury", "World Bank Pink Sheet", "BOJ FM08"],
    updated: "2026-05-07",
  },
  {
    slug: "us-2y-vs-jepx-tokyo",
    title: "米 2 年金利 × JEPX 東京：短期金融政策の電力卸価格への波及",
    lede: "FRB 政策金利 → 米 2y → 為替 → 燃料 → JEPX の経路、月次相関 r=+0.40-0.55",
    tags: ["金融", "金利", "電力", "東京", "FRB"],
    sources: ["U.S. Treasury", "JEPX スポット市場"],
    updated: "2026-05-07",
  },
  {
    slug: "us-cpi-vs-fx",
    title: "米 CPI × USD/JPY：インフレと為替の長い因果",
    lede: "米 CPI 前年比と USD/JPY 月中平均の 15 年相関、米インフレ → FRB 政策 → 米金利 → 為替の連鎖を可視化。月次相関 r=+0.55-0.70 (ラグ 3-6 ヶ月)",
    tags: ["金融", "為替", "USD/JPY", "マクロ", "CPI", "インフレ"],
    sources: ["FRED CPIAUCSL", "BOJ FM08"],
    updated: "2026-05-11",
  },
  {
    slug: "fed-funds-vs-jepx-tokyo",
    title: "Fed FF rate × JEPX 東京：米政策金利と日本電力卸価格の遠い因果",
    lede: "米 Fed Funds Rate と JEPX 東京の月次相関、米政策金利 → 為替 → 燃料 → JEPX の 4 段階連鎖。月次相関 r=+0.30-0.50 (ラグ 6-12 ヶ月)",
    tags: ["金融", "金利", "電力", "東京", "FRB", "マクロ"],
    sources: ["FRED FEDFUNDS", "JEPX スポット市場"],
    updated: "2026-05-11",
  },
  {
    slug: "us-industrial-vs-jp-demand",
    title: "米鉱工業生産 × 日本電力販売量：景気の海を越えた伝播",
    lede: "米景気 → 世界製造業 → 日本製造業 → 日本電力需要、リーマン + コロナ両ショック時に明瞭。ラグ 3-6 ヶ月で r=+0.45-0.60",
    tags: ["電力", "需要", "マクロ", "鉱工業生産", "景気サイクル", "ラグ相関"],
    sources: ["FRED INDPRO", "METI 電力調査統計"],
    updated: "2026-05-11",
  },
  {
    slug: "fuel-cost-decomp",
    title: "燃料コスト分解パネル: 世界市場 → 円建て → 燃料調達 → JEPX 卸価格",
    lede: "LNG / Brent / 石炭 → USD/JPY 換算 → 燃料調達 → JEPX 東京の 4 層伝播を 1 ページに統合。加法 3 要因分解で各層の寄与を可視化、Insight #13 の発展版",
    tags: ["燃料", "為替", "電力", "LNG", "東京", "要因分解", "ChartDecomp"],
    sources: ["World Bank Pink Sheet", "日本銀行", "JEPX スポット市場"],
    updated: "2026-05-13",
  },
  {
    slug: "us-employment-vs-fx-vs-jepx",
    title: "米雇用統計 × USD/JPY × JEPX：マクロが電力に届くまでの 4 段階",
    lede: "米 Nonfarm Payrolls (前月差) と失業率を USD/JPY × JEPX 東京と並べる 3 軸対比。米雇用 → FRB → 米金利 → 為替 → 円建て燃料 → 日本電力市場の 4-6 段階伝播。失業率 × USD/JPY r=-0.62 (ラグ 6 ヶ月)、USD/JPY × JEPX 東京 r=+0.71 (同月)",
    tags: ["金融", "マクロ", "為替", "USD/JPY", "電力", "東京", "米雇用統計", "失業率", "NFP"],
    sources: ["FRED PAYEMS", "FRED UNRATE", "BOJ FM08", "JEPX スポット市場"],
    updated: "2026-05-15",
  },
  {
    slug: "us-unemployment-vs-jp-demand",
    title: "米失業率 × 日本電力需要：景気波及の長いトンネル",
    lede: "米失業率と日本電力販売量のラグ相関を 0-12 ヶ月で走査。リーマンショック余波で 9 ヶ月遅れ、コロナ同時ショックで同月連動。月次相関 r=-0.45〜-0.65 (ラグ 6-9 ヶ月)",
    tags: ["金融", "マクロ", "電力", "需要", "失業率", "ラグ相関", "景気サイクル"],
    sources: ["FRED UNRATE", "METI 電力調査統計"],
    updated: "2026-05-15",
  },
  {
    slug: "us-food-cpi-vs-yen-lng",
    title: "米食料 CPI × 円建て LNG：穀物とエネルギーが同じ風で動く理由",
    lede: "米食料 CPI 前年比と円建て LNG 価格を並べる。ウクライナ戦争後の穀物 + エネルギー同時急騰、ドル建て輸入物価 + 円安効果の二重ショック構造を解読。月次相関 r=+0.74 (2018-2025)",
    tags: ["金融", "燃料", "為替", "LNG", "経済", "食料", "CPI", "ウクライナ戦争"],
    sources: ["FRED CPIUFDSL", "World Bank Pink Sheet", "BOJ FM08"],
    updated: "2026-05-15",
  },
  {
    slug: "tankan-vs-industrial-vs-demand",
    title: "日銀短観 × 鉱工業生産 × 電力需要：景況感が電気に届くまでの 3 軸",
    lede: "日銀短観 大企業製造業 DI と鉱工業生産 + 日本電力需要の 3 軸対比。景況感 → 実体経済 → 電力市場の伝播を 30 年データで可視化。月次相関 r=+0.55〜+0.65 (ラグ 6 ヶ月)",
    tags: ["金融", "マクロ", "電力", "需要", "日銀短観", "DI", "鉱工業生産", "景況感"],
    sources: ["日本銀行 短観", "FRED INDPRO", "METI 電力調査統計"],
    updated: "2026-05-15",
  },
];

export function searchInsights(
  insights: Insight[],
  query: string | null | undefined,
): Insight[] {
  if (!query) return insights;
  const q = query.trim().toLowerCase();
  if (!q) return insights;
  return insights.filter((i) => {
    if (i.slug.toLowerCase().includes(q)) return true;
    if (i.title.toLowerCase().includes(q)) return true;
    if (i.lede.toLowerCase().includes(q)) return true;
    if (i.tags.some((t) => t.toLowerCase().includes(q))) return true;
    return false;
  });
}
