export interface Insight {
  slug: string;
  title: string;
  lede: string;
  tags: string[];
  sources: string[];
  updated: string;
}

export const INSIGHTS: Insight[] = [
  {
    slug: "temp-vs-price",
    title: "気温 × 電力価格：東京 15 年史",
    lede: "JMA 日平均気温と JEPX 東京エリア卸電力価格の 15 年相関",
    tags: ["電力", "気象", "東京"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-02",
  },
  {
    slug: "temp-min-hokkaido-vs-price",
    title: "札幌最低気温 × 北海道 JEPX：冬の暖房需要 15 年",
    lede: "寒さが厳しいほど電気代が上がる構造。北本連系線の制約と暖房需要の関係",
    tags: ["電力", "気象", "北海道"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-max-kyushu-vs-price",
    title: "福岡最高気温 × 九州 JEPX：太陽光と冷房需要の綱引き",
    lede: "太陽光発電大国・九州ならではの「夏の昼に価格が下がり、夜に上がる」非対称性",
    tags: ["電力", "気象", "九州", "太陽光"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-max-tokyo-summer",
    title: "東京最高気温 × 東京 JEPX：夏期 6-9 月の絶対偏差相関",
    lede: "25℃ から離れるほど価格が上がる U 字型構造を絶対偏差相関で可視化",
    tags: ["電力", "気象", "東京", "夏期"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-tohoku",
    title: "仙台日平均気温 × 東北 JEPX：火力依存エリアの夏冬両期需要",
    lede: "原発停止後の火力依存と、夏冬両期型需要が価格に響く構造",
    tags: ["電力", "気象", "東北", "原発"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-chubu",
    title: "名古屋日平均気温 × 中部 JEPX：製造業の電力需要パターン",
    lede: "トヨタ・自動車部品など製造業集積エリアの「平日 vs 休日」需要パターン",
    tags: ["電力", "気象", "中部", "製造業"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-kansai",
    title: "大阪日平均気温 × 関西 JEPX：原発再稼働と気温感応度の変化",
    lede: "高浜・大飯・美浜 7 基稼働でベースロード復活、気温感応度が 3 段階に変化",
    tags: ["電力", "気象", "関西", "原発"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-chugoku",
    title: "広島日平均気温 × 中国 JEPX：太陽光大規模導入エリアの昼間反転",
    lede: "国内 2 位の太陽光導入比率 + 島根 2 号機 2024 年再稼働の構造変化",
    tags: ["電力", "気象", "中国", "太陽光", "原発"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-shikoku",
    title: "高松日平均気温 × 四国 JEPX：小規模市場と原発再稼働",
    lede: "国内最小級市場、伊方 3 号機の運転 / 停止が価格に直接反映",
    tags: ["電力", "気象", "四国", "原発"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "temp-vs-price-hokuriku",
    title: "金沢日平均気温 × 北陸 JEPX：水力ベースロード × 豪雪需要",
    lede: "水力比率国内トップで平時は安定、豪雪期は暖房 + 融雪需要で価格上振れ",
    tags: ["電力", "気象", "北陸", "水力", "豪雪"],
    sources: ["JEPX スポット市場", "気象庁 日次気温"],
    updated: "2026-05-05",
  },
  {
    slug: "lng-vs-price-tokyo",
    title: "LNG × JEPX 東京：気温では説明できない価格",
    lede: "ドル建て LNG (CIF) × 円建て JEPX 東京の月次相関、ChartDual 2 軸時系列",
    tags: ["電力", "燃料", "東京", "LNG"],
    sources: ["World Bank Pink Sheet", "JEPX スポット市場"],
    updated: "2026-05-05",
  },
  {
    slug: "lng-lag-vs-price-tokyo",
    title: "LNG → JEPX 東京：何ヶ月遅れで価格に効くか",
    lede: "0-12 ヶ月のラグ相関スイープ、ピーク 5-6 ヶ月（長期契約 + 燃料費調整 + 在庫の 3 層）",
    tags: ["電力", "燃料", "東京", "LNG", "ラグ相関"],
    sources: ["World Bank Pink Sheet", "JEPX スポット市場"],
    updated: "2026-05-05",
  },
  {
    slug: "brent-lag-vs-price-tokyo",
    title: "Brent → JEPX 東京：原油は何ヶ月遅れて電力価格に伝播するか",
    lede: "原油 → LNG → JEPX の 2 段伝播、Brent ピークラグ 7-8 ヶ月（LNG より 1-3 ヶ月長い）",
    tags: ["電力", "燃料", "東京", "原油", "ラグ相関"],
    sources: ["World Bank Pink Sheet", "JEPX スポット市場"],
    updated: "2026-05-05",
  },
  {
    slug: "ttf-lag-vs-lng-jp",
    title: "TTF → 日本 LNG CIF：欧州ガス危機は何ヶ月遅れで日本に届くか",
    lede: "ドル建て × ドル建ての純粋燃料伝播、ピーク 3-4 ヶ月（燃料チェーン最上流）",
    tags: ["燃料", "LNG", "TTF", "ラグ相関"],
    sources: ["World Bank Pink Sheet"],
    updated: "2026-05-05",
  },
  {
    slug: "fx-decomp-lng-jepx-tokyo",
    title: "円安 × LNG × JEPX：2022-2023 価格上振れの要因分解",
    lede: "加法 3 要因分解（LNG 要因 + 円安要因 + 相乗効果）、基準月 2020-12 で電気代高騰の正体",
    tags: ["燃料", "為替", "LNG", "東京", "要因分解"],
    sources: ["World Bank Pink Sheet", "日本銀行"],
    updated: "2026-05-05",
  },
  {
    slug: "jgb-vs-yen-lng",
    title: "JGB × LNG：金利と燃料の同時動",
    lede: "10 年物日本国債利回り × LNG の 2 軸時系列、エネルギーと金融の引用インフラ中心軸",
    tags: ["金融", "燃料", "LNG", "JGB"],
    sources: ["World Bank Pink Sheet", "財務省 国債金利"],
    updated: "2026-05-05",
  },
  {
    slug: "precip-hokuriku-vs-price",
    title: "金沢降水量 × 北陸 JEPX：水力ベースロードと豪雪のサイクル",
    lede: "降水量 → ダム水位 → 春の水力出力増 → ベースロード安定の連鎖",
    tags: ["電力", "気象", "北陸", "水力", "降水量"],
    sources: ["JEPX スポット市場", "気象庁 日次降水量"],
    updated: "2026-05-05",
  },
  {
    slug: "precip-kyushu-vs-price",
    title: "福岡降水量 × 九州 JEPX：豪雨年の太陽光出力低下と需要抑制",
    lede: "太陽光大量導入下での降水量、太陽光低下と冷房需要抑制の両方向効果が同時発生",
    tags: ["電力", "気象", "九州", "太陽光", "降水量"],
    sources: ["JEPX スポット市場", "気象庁 日次降水量"],
    updated: "2026-05-06",
  },
  {
    slug: "solar-vs-sunshine-tokyo",
    title: "太陽光発電量 × 東京日照時間：発電ポテンシャルの可視化",
    lede: "全国太陽光発電量 × 東京日照時間の月次相関 +0.70-0.85、再エネのポテンシャル指標",
    tags: ["電力", "気象", "東京", "太陽光", "再エネ"],
    sources: ["METI 電力調査統計", "気象庁 日照時間"],
    updated: "2026-05-06",
  },
  {
    slug: "nuclear-vs-jepx-kansai",
    title: "原子力発電量 × JEPX 関西：再稼働 7 基のベースロード復活",
    lede: "高浜・大飯・美浜 7 基稼働で月次相関 -0.40〜-0.60、本州最安水準を維持",
    tags: ["電力", "原発", "関西", "ベースロード"],
    sources: ["METI 電力調査統計", "JEPX スポット市場"],
    updated: "2026-05-06",
  },
  {
    slug: "renewables-share-trend",
    title: "再エネ比率の 5 年トレンド：エネルギー基本計画 2030 年目標 36-38% への道のり",
    lede: "全国再エネ比率の 5 年月次トレンド、年率 +1.5%pt ペース、2030 年目標到達には加速が必要",
    tags: ["電力", "再エネ", "全国", "エネルギー基本計画"],
    sources: ["METI 電力調査統計", "エネルギー基本計画"],
    updated: "2026-05-06",
  },
  {
    slug: "thermal-vs-lng",
    title: "火力発電量 × LNG：直感的仮説の反証",
    lede: "LNG 高騰時も火力は減らない。火力 = 需要調整役、燃料コストは JEPX 価格に反映される構造",
    tags: ["電力", "燃料", "LNG", "火力"],
    sources: ["METI 電力調査統計", "World Bank Pink Sheet"],
    updated: "2026-05-06",
  },
  {
    slug: "demand-vs-temp",
    title: "販売電力量 × 全国気温：需要側の U 字パターン",
    lede: "需要は快適温度 20-25℃ で最低、絶対偏差で r=+0.65〜+0.75。冬偏重の構造を実証",
    tags: ["電力", "気象", "全国", "需要"],
    sources: ["METI 電力調査統計", "気象庁 日次気温"],
    updated: "2026-05-06",
  },
  {
    slug: "wind-vs-wind-hokkaido",
    title: "風力発電量 × 札幌風速：再エネ × 気象シリーズ 2 本目",
    lede: "全国風力 × 札幌風速、月次相関 r=+0.30〜+0.50（中程度）。地理的偏在で太陽光より弱い相関",
    tags: ["電力", "再エネ", "風力", "北海道"],
    sources: ["METI 電力調査統計", "気象庁 日次風速"],
    updated: "2026-05-06",
  },
  {
    slug: "wind-vs-wind-hokuriku",
    title: "風力発電量 × 金沢風速：日本海側冬季季節風の構造",
    lede: "金沢の冬期 6-8 m/s + 夏期 2-3 m/s の極端な振幅、北海道とは異なる位相",
    tags: ["電力", "再エネ", "風力", "北陸"],
    sources: ["METI 電力調査統計", "気象庁 日次風速"],
    updated: "2026-05-06",
  },
  {
    slug: "solar-sunshine-9-region-heatmap",
    title: "9 地点 × 36 ヶ月 日照時間ヒートマップ：太陽光ポテンシャルの地理性",
    lede: "瀬戸内海（広島・高松）の太陽光最有利 vs 日本海側（札幌・金沢）の不利、地理的格差を可視化",
    tags: ["電力", "再エネ", "太陽光", "ヒートマップ"],
    sources: ["気象庁 日次日照時間"],
    updated: "2026-05-06",
  },
  {
    slug: "wind-9-region-heatmap",
    title: "9 地点 × 36 ヶ月 風速ヒートマップ：陸上風力立地の地理的妥当性",
    lede: "金沢・札幌の冬季季節風が赤、太平洋側 + 内陸が穏やかで青。陸上風力立地集中の根拠（Day 11 で 9 地点完全体に拡張）",
    tags: ["電力", "再エネ", "風力", "ヒートマップ"],
    sources: ["気象庁 日次風速"],
    updated: "2026-05-07",
  },
  {
    slug: "snow-9-region-heatmap",
    title: "9 地点 × 36 ヶ月 積雪ヒートマップ：雪国 vs 太平洋側の極端な格差",
    lede: "札幌 + 金沢のみ赤い帯、他 7 地点はほぼ青。水力ベースロード + 暖房需要の地理的根拠",
    tags: ["電力", "気象", "雪国", "ヒートマップ"],
    sources: ["気象庁 月次最深積雪"],
    updated: "2026-05-06",
  },
  {
    slug: "thermal-fuel-cost-decomp",
    title: "火力 × LNG 燃料コスト要因分解：Phase 2-A delivery の象徴",
    lede: "火力発電量 × LNG ドル建て CIF を加法 3 要因分解。基準月 2021-04 で燃料コスト増の 85-90% は燃料価格要因",
    tags: ["電力", "燃料", "LNG", "火力", "要因分解"],
    sources: ["METI 電力調査統計", "World Bank Pink Sheet"],
    updated: "2026-05-07",
  },
  {
    slug: "precip-9-region-heatmap",
    title: "9 地点 × 36 ヶ月 降水量ヒートマップ：3 つの気象パターンの重ね合わせ",
    lede: "北陸冬季豪雪 + 太平洋側梅雨 + 九州台風の 3 パターンが地理的にモザイク状に重なる構造、再エネ + 需要への 3 経路",
    tags: ["電力", "気象", "降水量", "ヒートマップ"],
    sources: ["気象庁 日次降水量"],
    updated: "2026-05-07",
  },
  {
    slug: "temp-9-region-heatmap",
    title: "9 地点 × 36 ヶ月 平均気温ヒートマップ：年周期と温暖化トレンド",
    lede: "9 地点すべてが年周期で揃う唯一の気象変数、緯度差 14℃ の地理的偏在 + 2023-2025 年の高温 3 連続",
    tags: ["電力", "気象", "気温", "ヒートマップ"],
    sources: ["気象庁 日次気温"],
    updated: "2026-05-07",
  },
  {
    slug: "multi-region-jepx-comparison",
    title: "9 エリア JEPX 比較：地域差の構造と原因",
    lede: "9 エリアの卸電力価格を 1 ページで比較、原発再稼働 / 太陽光導入 / 火力依存 / 水力比率の刻印を可視化",
    tags: ["電力", "全国", "JEPX", "原発", "太陽光"],
    sources: ["JEPX スポット市場"],
    updated: "2026-05-07",
  },
  {
    slug: "region-fuel-sensitivity",
    title: "9 エリア × LNG 価格感応度：原発再稼働状況の刻印",
    lede: "原発再稼働済の関西 + 九州（r=+0.30）vs 火力依存の東京 + 中部（r=+0.65）、電源構成の経済効果を数値化",
    tags: ["電力", "燃料", "LNG", "全国", "原発"],
    sources: ["World Bank Pink Sheet", "JEPX スポット市場"],
    updated: "2026-05-07",
  },
  {
    slug: "spread-us-jp-10y-vs-fx",
    title: "日米 10 年金利差 × USD/JPY：円安要因の本丸",
    lede: "米 10y − 日 10y のスプレッドと USD/JPY の月次相関 r=+0.75-0.85、為替を駆動する金利差の構造",
    tags: ["金融", "金利", "為替", "USD/JPY"],
    sources: ["U.S. Treasury", "財務省 国債金利", "BOJ FM08"],
    updated: "2026-05-07",
  },
  {
    slug: "us-yield-curve-vs-jp-demand",
    title: "米国イールドカーブ × 日本電力需要：景気波及の長いトンネル",
    lede: "米 30y − 米 2y と日本販売電力量、12-18 ヶ月遅延の景気サイクル波及を可視化",
    tags: ["金融", "金利", "電力", "需要", "景気サイクル"],
    sources: ["U.S. Treasury", "METI 電力調査統計"],
    updated: "2026-05-07",
  },
  {
    slug: "us-30y-vs-jgb-30y",
    title: "米 30 年金利 × 日本 30 年 JGB：超長期金利の連動と乖離",
    lede: "Phase 3-B で jgb-30y-yield 着地、超長期金利のグローバル連動 + YCC 期の日本独自性を初めて 1 ページで可視化",
    tags: ["金融", "金利", "超長期", "JGB"],
    sources: ["U.S. Treasury", "財務省 国債金利"],
    updated: "2026-05-07",
  },
  {
    slug: "us-10y-vs-yen-lng",
    title: "米 10 年金利 × 円建て LNG：米金融政策の燃料コストへの影響",
    lede: "米金融政策 → 米金利 → 為替 → 日本の燃料コストの伝播経路、Insight #16 の続編で米国側からの視点",
    tags: ["金融", "金利", "燃料", "LNG", "為替"],
    sources: ["U.S. Treasury", "World Bank Pink Sheet", "BOJ FM08"],
    updated: "2026-05-07",
  },
  {
    slug: "us-2y-vs-jepx-tokyo",
    title: "米 2 年金利 × JEPX 東京：短期金融政策の電力卸価格への波及",
    lede: "FRB 政策金利 → 米 2y → 為替 → 燃料 → JEPX の経路、月次相関 r=+0.40-0.55",
    tags: ["金融", "金利", "電力", "東京", "FRB"],
    sources: ["U.S. Treasury", "JEPX スポット市場"],
    updated: "2026-05-07",
  },
  {
    slug: "us-cpi-vs-fx",
    title: "米 CPI × USD/JPY：インフレと為替の長い因果",
    lede: "米 CPI 前年比と USD/JPY 月中平均の 15 年相関、米インフレ → FRB 政策 → 米金利 → 為替の連鎖を可視化。月次相関 r=+0.55-0.70 (ラグ 3-6 ヶ月)",
    tags: ["金融", "為替", "USD/JPY", "マクロ", "CPI", "インフレ"],
    sources: ["FRED CPIAUCSL", "BOJ FM08"],
    updated: "2026-05-11",
  },
  {
    slug: "fed-funds-vs-jepx-tokyo",
    title: "Fed FF rate × JEPX 東京：米政策金利と日本電力卸価格の遠い因果",
    lede: "米 Fed Funds Rate と JEPX 東京の月次相関、米政策金利 → 為替 → 燃料 → JEPX の 4 段階連鎖。月次相関 r=+0.30-0.50 (ラグ 6-12 ヶ月)",
    tags: ["金融", "金利", "電力", "東京", "FRB", "マクロ"],
    sources: ["FRED FEDFUNDS", "JEPX スポット市場"],
    updated: "2026-05-11",
  },
  {
    slug: "us-industrial-vs-jp-demand",
    title: "米鉱工業生産 × 日本電力販売量：景気の海を越えた伝播",
    lede: "米景気 → 世界製造業 → 日本製造業 → 日本電力需要、リーマン + コロナ両ショック時に明瞭。ラグ 3-6 ヶ月で r=+0.45-0.60",
    tags: ["電力", "需要", "マクロ", "鉱工業生産", "景気サイクル", "ラグ相関"],
    sources: ["FRED INDPRO", "METI 電力調査統計"],
    updated: "2026-05-11",
  },
  {
    slug: "fuel-cost-decomp",
    title: "燃料コスト分解パネル: 世界市場 → 円建て → 燃料調達 → JEPX 卸価格",
    lede: "LNG / Brent / 石炭 → USD/JPY 換算 → 燃料調達 → JEPX 東京の 4 層伝播を 1 ページに統合。加法 3 要因分解で各層の寄与を可視化、Insight #13 の発展版",
    tags: ["燃料", "為替", "電力", "LNG", "東京", "要因分解", "ChartDecomp"],
    sources: ["World Bank Pink Sheet", "日本銀行", "JEPX スポット市場"],
    updated: "2026-05-13",
  },
  {
    slug: "us-employment-vs-fx-vs-jepx",
    title: "米雇用統計 × USD/JPY × JEPX：マクロが電力に届くまでの 4 段階",
    lede: "米 Nonfarm Payrolls (前月差) と失業率を USD/JPY × JEPX 東京と並べる 3 軸対比。米雇用 → FRB → 米金利 → 為替 → 円建て燃料 → 日本電力市場の 4-6 段階伝播。失業率 × USD/JPY r=-0.62 (ラグ 6 ヶ月)、USD/JPY × JEPX 東京 r=+0.71 (同月)",
    tags: ["金融", "マクロ", "為替", "USD/JPY", "電力", "東京", "米雇用統計", "失業率", "NFP"],
    sources: ["FRED PAYEMS", "FRED UNRATE", "BOJ FM08", "JEPX スポット市場"],
    updated: "2026-05-15",
  },
  {
    slug: "us-unemployment-vs-jp-demand",
    title: "米失業率 × 日本電力需要：景気波及の長いトンネル",
    lede: "米失業率と日本電力販売量のラグ相関を 0-12 ヶ月で走査。リーマンショック余波で 9 ヶ月遅れ、コロナ同時ショックで同月連動。月次相関 r=-0.45〜-0.65 (ラグ 6-9 ヶ月)",
    tags: ["金融", "マクロ", "電力", "需要", "失業率", "ラグ相関", "景気サイクル"],
    sources: ["FRED UNRATE", "METI 電力調査統計"],
    updated: "2026-05-15",
  },
  {
    slug: "us-food-cpi-vs-yen-lng",
    title: "米食料 CPI × 円建て LNG：穀物とエネルギーが同じ風で動く理由",
    lede: "米食料 CPI 前年比と円建て LNG 価格を並べる。ウクライナ戦争後の穀物 + エネルギー同時急騰、ドル建て輸入物価 + 円安効果の二重ショック構造を解読。月次相関 r=+0.74 (2018-2025)",
    tags: ["金融", "燃料", "為替", "LNG", "経済", "食料", "CPI", "ウクライナ戦争"],
    sources: ["FRED CPIUFDSL", "World Bank Pink Sheet", "BOJ FM08"],
    updated: "2026-05-15",
  },
  {
    slug: "tankan-vs-industrial-vs-demand",
    title: "日銀短観 × 鉱工業生産 × 電力需要：景況感が電気に届くまでの 3 軸",
    lede: "日銀短観 大企業製造業 DI と鉱工業生産 + 日本電力需要の 3 軸対比。景況感 → 実体経済 → 電力市場の伝播を 30 年データで可視化。月次相関 r=+0.55〜+0.65 (ラグ 6 ヶ月)",
    tags: ["金融", "マクロ", "電力", "需要", "日銀短観", "DI", "鉱工業生産", "景況感"],
    sources: ["日本銀行 短観", "FRED INDPRO", "METI 電力調査統計"],
    updated: "2026-05-15",
  },
  {
    slug: "geothermal-vs-volcanic-temp",
    title: "地熱発電 × 火山地帯気温偏差：日本固有のベースロード電源とその気象独立性",
    lede: "地熱発電量と東北気温 (火山地帯代理) の月次相関を検証。地熱は設備利用率 70-80% で気象相関 r ≈ 0、太陽光 (+0.85) ・風力 (+0.65〜+0.75) との対照で再エネ多様化の価値を構造的に説明",
    tags: ["電力", "再エネ", "地熱", "ベースロード", "気象独立性", "東北"],
    sources: ["METI 電力調査統計", "気象庁 日次気温"],
    updated: "2026-05-15",
  },
  // Insight #48 eu-ets-vs-yen-lng は 2026-05-27 に draft 退避 (Phase 2 batch 2 remediation)。
  // catalog の eu-ets-eua-monthly 未着地のためチャートが描画できず、公開 Insight
  // 一覧から除外。MDX は src/content/drafts/eu-ets-vs-yen-lng/page.mdx に退避。
  {
    slug: "china-pmi-vs-lng-asia",
    title: "中国 NBS 製造業 PMI × LNG アジア需要：世界第 2 位経済の景気が日本電力価格に届くまで",
    lede: "中国 NBS 官製 製造業 PMI (china-nbs-mfg-pmi) と円建て LNG 日本 CIF を 2 軸 + 短期ラグで定性的に対比。世界第 2 位経済の景気変動 → アジア LNG 需給 → 日本電力市場の連動構造を解説。観測期間は 2025-04〜2026-04 の 13 ヶ月で短く、相関の強弱は断定しない (L-051 / L-062)",
    tags: ["燃料", "国際", "中国", "PMI", "LNG", "アジア需給", "NBS"],
    sources: ["NBS 中国国家統計局 製造業 PMI", "World Bank Pink Sheet", "BOJ FM08"],
    updated: "2026-05-27",
  },
  {
    slug: "ecb-rate-vs-eurusd-vs-usdjpy",
    title: "ECB 政策金利 × USD/EUR × USD/JPY：3 大金利政策の三角関係",
    lede: "ECB 主要リファイナンス金利 (MRR、`ecb-rate-mrr`、月次、%) × USD/EUR + USD/JPY の 3 軸対比。日米欧 3 大中央銀行 (BOJ + FRB + ECB) の金利政策が世界為替市場に与える複合効果を、2023 年 5 月以降（ECB 利上げ完了〜利下げ転換局面）の約 3 年データで可視化、円安進行の三角構造と利下げ局面の歩調を解読",
    tags: ["金融", "国際", "ECB", "中央銀行", "為替", "USD/EUR", "USD/JPY"],
    sources: ["ECB SDW", "BOJ FM08", "FRED FEDFUNDS"],
    updated: "2026-05-16",
  },
  {
    slug: "china-pmi-vs-jp-demand",
    title: "中国 NBS 製造業 PMI × 日本電力需要：世界第 2 位経済の景気が日本工業電力に届くトンネル",
    lede: "中国 NBS 官製 製造業 PMI (china-nbs-mfg-pmi、月次、index) と日本電力販売量 (meti-demand-total、月次、GWh) を 2 軸 + 短期ラグで定性的に対比。中国景気減速 → 日本輸出減 → 日本製造業稼働低下 → 電力需要減という長いトンネルの構造を解説。観測期間は 2025-04〜2026-04 の 13 ヶ月で短く、相関の強弱は断定しない (L-051 / L-062)",
    tags: ["電力", "需要", "国際", "中国", "PMI", "マクロ", "製造業", "NBS"],
    sources: ["NBS 中国国家統計局 製造業 PMI", "METI 電力調査統計"],
    updated: "2026-05-27",
  },
  {
    slug: "iron-ore-vs-thermal-power",
    title: "鉄鉱石 × 火力発電：鉄鋼業を介した「資源価格 → 国内電力需要」の隠れた連動",
    lede: "鉄鉱石価格 (Pink Sheet、月次、$/dmt) と火力発電量 (meti-gen-thermal、月次、GWh) の関係を可視化。世界第 3 位の鉄鋼生産国・日本における鉄鋼業電力需要 (年 35 TWh、全体の 4%) を介した間接因果、ラグ 6 ヶ月で月次相関 r=-0.30〜-0.45 (弱-中程度負相関)",
    tags: ["燃料", "電力", "国際", "鉄鋼", "資源", "鉄鉱石", "火力"],
    sources: ["World Bank Pink Sheet", "METI 電力調査統計", "日本鉄鋼連盟"],
    updated: "2026-05-16",
  },
  {
    slug: "hokkaido-heating-vs-snow",
    title: "北海道暖房 × 雪国電力：氷点下 -10℃ 時の極寒需要と電源構成の特殊性",
    lede: "札幌最低気温と北海道 JEPX の冬季 (11-3 月) 集中相関を可視化。-10℃ 以下の極寒で発現する暖房需要急増 + 北本連系線制約 (90 万 kW、需要の 15%) + 火力依存 60% の特殊構造、冬季限定で月次相関 r=-0.72〜-0.85 (本州他エリアより強い負相関)",
    tags: ["気象", "電力", "北海道", "暖房", "JEPX", "連系線", "冬季"],
    sources: ["気象庁 札幌", "JEPX スポット市場"],
    updated: "2026-05-16",
  },
  {
    slug: "okinawa-island-power-structure",
    title: "沖縄島嶼電力構造：本土と連系しない離島系統の特殊性",
    lede: "沖縄電力 (沖縄本島 + 離島 11 系統) の島嶼電力構造を可視化。日本唯一 JEPX 不参加 + 本土連系線ゼロ + 火力依存 90% 超 + 燃料費調整制度のダイレクト影響という閉鎖系電力市場、北海道 (Insight #53) との対比で本土 7 エリア標準構造を浮き彫りに",
    tags: ["燃料", "電力", "沖縄", "島嶼", "閉鎖系", "火力", "燃料費調整"],
    sources: ["沖縄電力", "OCCTO", "METI 電力調査統計"],
    updated: "2026-05-16",
  },
  {
    slug: "fx-resilience-by-region",
    title: "円安耐性 × エリア別卸電力：9 エリアの「為替ショック連動度」格差",
    lede: "JEPX 9 エリア (北海道〜九州) の月次卸価格と円建て LNG (fuel-lng-jp-cif × fx-usdjpy-monthly-avg) のラグなし相関を 2012-04〜2025-12 の 165 ヶ月で実測。九州 r=+0.31 〜 中部 r=+0.53 の 0.22 格差、北海道は意外にも耐性 2 位 (r=+0.39、気温・需給駆動)",
    tags: ["電力", "金融", "JEPX", "為替", "円安", "エリア比較", "電源構成"],
    sources: ["JEPX スポット市場", "World Bank Pink Sheet", "BOJ FM08", "METI 電力調査統計"],
    updated: "2026-05-16",
  },
  {
    slug: "global-lng-price-comparison",
    title: "国際 LNG プライス比較：JKM × TTF × Henry Hub × 日本 CIF の地理的価格差構造",
    lede: "アジア LNG (JKM)、欧州 (TTF)、米国 (Henry Hub)、日本 CIF の 4 地域価格を 15 年比較。輸送コスト + 長期契約 + 地政学による地理的価格差を可視化、ウクライナ戦争後の構造変化 (2022-08 で TTF $95/JKM $70/CIF $24.5 の歴史的最大格差) を読み解く",
    tags: ["燃料", "国際", "LNG", "JKM", "TTF", "Henry Hub", "地理的価格差"],
    sources: ["FRED MHHNGSP", "World Bank Pink Sheet", "Platts JKM"],
    updated: "2026-05-16",
  },
  {
    slug: "japan-cpi-vs-yen-energy",
    title: "日本 CPI × 円建てエネルギー × 家計負担：エネルギー輸入価格が家計に届くまで",
    lede: "日本 CPI 総合 (jpn-cpi-yoy、月次、%) と円建て LNG / 原油 (fuel-lng-jp-cif × fx-usdjpy-monthly-avg、円/MMBtu) のラグ相関を 0-12 ヶ月で走査。燃料費調整 → 電気代 → 物価指数の 3-9 ヶ月伝播、ラグ 6 ヶ月で月次相関 r=+0.65〜+0.80",
    tags: ["金融", "燃料", "需要", "CPI", "エネルギー", "家計", "為替", "円安"],
    sources: ["総務省統計局 CPI", "World Bank Pink Sheet", "BOJ FM08"],
    updated: "2026-05-16",
  },
  {
    slug: "japan-industrial-vs-power",
    title: "日本鉱工業生産 × 電力需要：実体経済が電力に届く即時相関と長期トレンド",
    lede: "日本鉱工業生産指数 (jpn-industrial-production、月次、2020=100) と電力販売量 (meti-demand-total、月次、GWh) のラグなし + ラグ相関 0-12 ヶ月走査。製造業稼働 → 電力需要のラグなし即時連動 (r=+0.78〜+0.85)、米/中の 9 ヶ月遅延と対比",
    tags: ["電力", "需要", "鉱工業", "製造業", "実体経済", "マクロ"],
    sources: ["METI 鉱工業生産指数", "METI 電力調査統計"],
    updated: "2026-05-16",
  },
  {
    slug: "fuel-chain-overview",
    title: "燃料チェーン俯瞰：欧州 TTF → 日本 LNG → JEPX の伝播経路",
    lede: "Insight #11-#15 を 1 ページに統合。欧州ガス危機（TTF）から日本の電気代（JEPX）まで、燃料チェーン 3 層 + 為替要因分解の全体像を俯瞰、北極星「引用インフラ」の象徴記事",
    tags: ["燃料", "金融", "為替", "電力", "LNG", "TTF", "Brent", "JEPX"],
    sources: ["World Bank Pink Sheet", "日本銀行 FM08", "JEPX"],
    updated: "2026-05-17",
  },
  {
    slug: "fed-funds-vs-fx",
    title: "FF レート × USD/JPY：FRB 政策金利と為替の直結",
    lede: "米 FF レート (FRED FEDFUNDS) と USD/JPY 月中平均の相関を見る。FRB の利上げ・利下げが為替に即時反映される構造を可視化、Insight #35 (日米金利差) との対比で説明力の差を実証",
    tags: ["金融", "為替", "金利", "米国", "FRB", "FF レート"],
    sources: ["FRED FEDFUNDS", "日本銀行 FM08"],
    updated: "2026-05-18",
  },
  {
    slug: "capacity-market-5-year-trends",
    title: "容量市場メインオークション 6 年推移 — 電源投資シグナルとしての kW 価値",
    lede: "OCCTO 容量市場メインオークション約定結果 (FY2024-FY2029、6 年分) の全国加重平均価格 14,137 → 3,737 → 6,230 → 8,992 → 12,210 → 13,909 ¥/kW とエリア別分化構造を実 CSV データで可視化。「初回高値 → 暴落 → V 字回復」の制度的ドラマと、太陽光大量導入の九州が高値になる kW 価値の本質を読み解く",
    tags: ["電力", "容量市場", "電源投資", "OCCTO", "kW 価値", "火力", "再エネ"],
    sources: ["OCCTO 容量市場メインオークション約定結果", "容量市場ガイドライン (経済産業省)"],
    updated: "2026-05-21",
  },
  {
    slug: "balancing-market-5-products-comparison",
    title: "需給調整市場 商品別 約定価格の構造 — 6 系列の年間平均落札単価で読む市場設計",
    lede: "EPRX 年次取りまとめより、需給調整市場 6 商品 (一次・二次①②・三次①②・複合) の年間平均落札単価を可視化。FY2024 は 2.67〜3.30 円/ΔkW・30分の狭い帯に収まり、商品差は価格より調達不足率に現れる。蓄電池・VPP の上限価格付近の高値応札が市場構造を変えつつある",
    tags: ["電力", "需給調整市場", "EPRX", "ΔkW", "周波数調整", "蓄電池"],
    sources: ["電力需給調整力取引所 (EPRX) 取引実績の取りまとめ結果"],
    updated: "2026-05-23",
  },
  {
    slug: "tertiary-balance-vs-jepx",
    title: "三次調整力② × JEPX — 需給調整単価と卸価格・燃料の年次連動 (2021〜)",
    lede: "需給調整市場で唯一 5 年取れる長期系列・三次調整力② (FY2021 2.58 → FY2022 3.49 → FY2023 1.46 → FY2024 3.30 → FY2025 上期 1.14 円/ΔkW・30分) と JEPX スポット価格・燃料価格の連動を年次粒度で可視化。EPRX 公表の相関係数は 0.80 → 0.70 → 0.37 と低下、燃料局面で連動し平時で乖離する構造を読み解く",
    tags: ["電力", "需給調整市場", "EPRX", "三次調整力", "JEPX", "燃料"],
    sources: ["電力需給調整力取引所 (EPRX) 取引実績の取りまとめ結果", "JEPX スポット市場"],
    updated: "2026-05-23",
  },
  {
    slug: "capacity-market-area-vs-power-mix",
    title: "容量市場エリア別約定価格の地理構造 — 東日本・九州が高く、西日本 60Hz が安い理由 (FY2028)",
    lede: "OCCTO 容量市場メインオークション (FY2028 実需給向け) のエリア別価格 14,812 / 13,177 / 10,280 / 8,785 ¥/kW の 4 価格帯構造を、連系線制約 + 電源構成 + 需要パターンで読み解く。「東京は大需要地だから安い」「九州は太陽光が多いから安い」という 2 つの直感を実データで反証",
    tags: ["電力", "容量市場", "エリア別", "OCCTO", "連系線", "電源構成", "kW 価値", "太陽光", "九州", "東京"],
    sources: ["OCCTO 容量市場メインオークション約定結果", "資源エネルギー庁 電力調査統計"],
    updated: "2026-05-24",
  },
  {
    slug: "balancing-source-type-comparison",
    title: "需給調整市場の電源種別別 落札単価 — 蓄電池・VPP の高値と揚水の基準線（FY2024〜）",
    lede: "EPRX 年次取りまとめより、需給調整市場の電源種別別 (揚水 / 蓄電池 / VPP) 平均落札単価を商品別に対比。三次調整力② FY2024 で 揚水 0.72 / 蓄電池 109.43 / VPP 46.24 円/ΔkW・30分 という二極構造を可視化。ただし単価は volume-weighted でなく「約定時の単価水準」であり、市場全体の単価でも市場寄与でもない点を明示",
    tags: ["電力", "需給調整市場", "電源種別", "蓄電池", "VPP", "揚水", "ΔkW"],
    sources: ["電力需給調整力取引所 (EPRX) 取引実績の取りまとめ結果"],
    updated: "2026-05-25",
  },
  {
    slug: "ecb-fed-rate-diff-vs-eurusd",
    title: "ECB と Fed、どちらが利上げに速いか — 政策金利差で読む EUR/USD",
    lede: "ECB 預金ファシリティ金利 (DFR) − 米 実効フェデラルファンド金利 (% pt) のスプレッドと EUR/USD 月平均 (USD/EUR) を ChartSpread で重ね描き。金利平価の発想で「中央銀行のどちらが速く動いたか」が EUR/USD の背骨になるかを、2023 年以降（ECB 利上げ完了〜利下げ転換局面）の約 3 年データで確かめる、Phase 2 国際ドメイン第 1 弾",
    tags: ["国際", "金融", "金利", "為替", "ECB", "Fed", "EUR/USD"],
    sources: ["ECB Data Portal (DFR + EUR/USD Reference Rate)", "FRED FEDFUNDS"],
    updated: "2026-05-26",
  },
  {
    slug: "world-power-co2-intensity",
    title: "電気の「きれいさ」を主要5か国で比べる — 日本の電力 CO2 強度はどこに立つか",
    lede: "Ember Monthly Electricity Data (CC-BY-4.0、catalog 205) の電力部門 CO2 強度 (gCO2/kWh、月次) を主要 5 か国 (日本・米国・中国・ドイツ・英国) で並べ、日本がどこに立っているかを確かめる。2025-12 で 中国 592 / 日本 476 / 米国 384 / ドイツ 357 / 英国 192 gCO2/kWh、日本は中国に次いで 2 番目に高く、英国比で約 2.5 倍。電源構成 (石炭依存度・原子力・再エネ) の刻印を読み解く、Phase 2 国際ドメイン Ember 第 1 弾",
    tags: ["国際", "電力", "CO2", "脱炭素", "電源構成", "Ember"],
    sources: ["Ember Monthly Electricity Data (CC-BY-4.0)"],
    updated: "2026-05-28",
  },
  {
    slug: "world-power-mix-compare",
    title: "なぜ日本の電気は CO2 強度が高いのか — 主要 5 か国の電源構成で読み解く",
    lede: "Ember Monthly Electricity Data (CC-BY-4.0、catalog 240、5 か国 × 7 燃料 = 35 系列の ember-share-{fuel}-{cc}) で主要 5 か国の電源別発電量シェアを並べ、#67 の CO2 強度ランキングを電源構成から説明する。2025-12 で 中国 石炭 58.5% / 日本 石炭 32.0% + ガス 30.7% / 米国 ガス 38.2% / ドイツ 再エネ 54% + 原子力 0% / 英国 石炭 0% + 再エネ 56% という分岐。CO2 強度を最も強く規定するのは石炭シェアであることを実データで示す、Phase 2 国際ドメイン Ember 第 2 弾",
    tags: ["国際", "電力", "電源構成", "脱炭素", "石炭", "再エネ", "Ember"],
    sources: ["Ember Monthly Electricity Data (CC-BY-4.0)"],
    updated: "2026-05-28",
  },
  {
    slug: "japan-power-mix-trend",
    title: "日本の電源構成この 8 年 — 火力依存の固定、原子力の部分回復、再エネの伸び",
    lede: "Ember Monthly Electricity Data (CC-BY-4.0、catalog 240、ember-share-{coal/gas/nuclear/solar/wind/hydro/bioenergy}-jp の 7 系列) で日本一国の電源別発電量シェアを 2018-04〜2026-02 の月次で追う。化石 (石炭 + ガス) は 67% → 63% でほぼ横ばい、原子力は 4% 台 → 9% 前後へ部分回復、太陽光は同月比 (4 月) で 9.0% → 13.8%、バイオは 2% → 7% 台。#67 / #68 の国際比較で見た「火力依存・原子力低位」を時系列で裏付ける、Phase 2 国際ドメイン Ember 第 3 弾 (日本単独)",
    tags: ["電力", "電源構成", "再エネ", "脱炭素", "原子力", "Ember"],
    sources: ["Ember Monthly Electricity Data (CC-BY-4.0)"],
    updated: "2026-05-28",
  },
  {
    slug: "jepx-tokyo-monthly-regression",
    title: "JEPX 東京 月次価格の回帰分析 — 何がどれだけ説明するか",
    lede: "JEPX 東京の月次価格を残余系統需要・円建て LNG・東京気温・前月価格で OLS 回帰し、係数・標準誤差・t 値・R² をすべて開示する教材。n=44 (2022-05〜2025-12) で R²=0.883、ただし前月価格 1 変数だけでも R²=0.834 — 説明力の大半は時系列の慣性。統計的に有意なのは気温 (t=4.01) と前月価格 (t=6.78) で、残余需要・円建て LNG は t<2。過去データの当てはまり (in-sample fit) であり未来予測ではない (リク監修済)、引用インフラ第 3 層「方法論ライブラリ」Day 1。",
    tags: ["電力", "JEPX", "回帰分析", "方法論", "統計", "データリテラシー"],
    sources: [
      "JEPX スポット市場",
      "METI 電力調査統計",
      "気象庁 日次気温",
      "World Bank Pink Sheet",
      "日本銀行 FM08",
    ],
    updated: "2026-05-29",
  },
  {
    slug: "holiday-power-pattern-jepx",
    title: "電力の \"休んでいる日\" — GW・盆・年末年始で JEPX 価格はどう動くか",
    lede: "JEPX 東京 日次価格 (2021-2025) と METI 月次需要 (2022-2025) で、GW・盆・年末年始という 3 つの休日窓の価格凹率を比較。GW −36% / 盆 −19% / 年末年始 −1% の差を「産業休止 × 気候 (暖冷房需要)」の枠組みで説明する教材。GW は気温が穏やかで暖冷房需要が需要を支えないため最大の凹み (5 月需要 61,951 GWh は年間最低、2025-05-05 は 6.99 円/kWh)。過去データの記述的分析であって未来予測ではない (リク監修済)、引用インフラ第 3 層「方法論ライブラリ」Day 2。",
    tags: ["電力", "JEPX", "需要", "休日", "季節性", "方法論", "データリテラシー"],
    sources: ["JEPX スポット市場", "METI 電力調査統計"],
    updated: "2026-05-30",
  },
  {
    slug: "forecast-error-baseline-jepx",
    title: "予測の \"下限ベンチマーク\" — 月次 JEPX を単純モデル4種で当てる",
    lede: "月次 JEPX 東京を 4 つの単純ベースライン (持続予測 lag1 / 季節平均 / 12 ヶ月前同値 / 訓練期間平均) で out-of-sample 予測し、MAE・RMSE・MAPE を全開示する教材。訓練 2012-2021 → テスト 2022-01〜2026-04 (n=52) で、持続予測 (前月と同じ) が MAE 2.02 円/kWh・MAPE 11.94% で最良。季節平均 23.54% / 12 ヶ月前 49.77% の約 2〜4 倍に圧勝し、誤差は ±2 円以内 65.4% (34/52) ・±5 円以内 88.5% (46/52) ・中央値誤差 −0.21 円でほぼ無バイアス。訓練平均 11.88 円 → テスト平均 16.14 円の構造的水準シフトで定数モデルは破綻。#70 の in-sample 回帰 (前月価格 1 変数で R²=0.834) を out-of-sample 側から裏付ける。過去データの out-of-sample 検証であって未来予測ではない (リク監修済)、引用インフラ第 3 層「方法論ライブラリ」Day 3。",
    tags: ["電力", "JEPX", "予測", "方法論", "統計", "データリテラシー"],
    sources: ["JEPX スポット市場"],
    updated: "2026-05-31",
  },
  {
    slug: "population-decline-vs-power-demand",
    title: "人口減少 × 電力需要：母数が縮む時代の電力",
    lede: "日本の総人口は 2019→2024 の 5 年で −2.2%（約 −275 万人）。同じ期間、全国の電力需要は −2.0% とほぼ同率で減った。一人当たり消費はほぼ横ばい（+0.1%）— 需要減のかなりの部分が「母数の縮小」で説明できる。47 都道府県の人口データで地域分化（東京 +3.9% vs 秋田 −11.3%）も見る。",
    tags: ["電力", "需要", "人口", "高齢化", "都道府県"],
    sources: ["e-Stat 人口推計", "Ember Monthly Electricity Data"],
    updated: "2026-06-07",
  },
  {
    slug: "lcoe-vs-power-mix",
    title: "LCOE × 電源構成：安い電源ほど日本では少ない",
    lede: "発電コスト（LCOE）が最も安い電源——陸上風力 $21/MWh・太陽光 $43/MWh（米 NREL ATB）——は、日本の電源構成では風力 1.3%・太陽光 4.1% と小さい。最大シェアは火力 73.7%。コストの序列と普及の順序がねじれている構造を、技術別 LCOE と日本の発電量シェアで並べて見る。",
    tags: ["電力", "再エネ", "電源構成", "LCOE", "コスト", "技術"],
    sources: ["NREL ATB", "METI 電力調査統計"],
    updated: "2026-06-08",
  },
  {
    slug: "eu-ets-vs-jp-gx",
    title: "EU ETS × 日本 GX-ETS：炭素価格20年の実績と、日本が立つ入口",
    lede: "EU ETS は20年で無償割当を約76%縮小し、発電・熱の燃料燃焼排出を2014年比で約55%削減した。日本の GX-ETS は2026年度に義務化、2033年度に発電部門を有償オークションへ。EU が歩んだ道のどこに日本が立つのかを EEA 実データで読む。",
    tags: ["ESG", "炭素価格", "EU ETS", "GX-ETS", "排出量取引", "国際", "電力"],
    sources: ["EEA EU ETS Data Viewer", "METI 排出量取引制度"],
    updated: "2026-06-09",
  },
  {
    slug: "eu-ets-allocation-gap-by-country",
    title: "EU ETS 排出 vs 無償割当：排出枠を市場で買っているのはどの国か",
    lede: "2025年、EU ETS 対象29か国の排出の約46%しか無償枠で覆われず、残り582Mtは市場で調達される。無償カバー率は石炭・島嶼の電力国ほど低く（ポーランド33%・アイルランド24%）、水力・原子力のクリーン電源国ほど高い（フランス84%・スウェーデン84%）。発電は原則オークションという設計が国別に映る。",
    tags: ["ESG", "炭素価格", "EU ETS", "排出量取引", "無償割当", "国際", "電力"],
    sources: ["EEA EU ETS Data Viewer", "METI 排出量取引制度"],
    updated: "2026-06-10",
  },
  {
    slug: "jp-energy-import-sources",
    title: "日本のエネルギーは誰から買っているか：原油・LNG・石炭の輸入相手国",
    lede: "2025年、日本は原油・LNG・石炭を計約18.7兆円輸入。原油は中東に94%依存（UAE43%+サウジ40%）、LNGは豪40%中心に分散（露9%・米7%）、石炭は豪67%の一極集中。燃料ごとに供給リスクの構造が異なる。",
    tags: ["地政", "エネルギー安全保障", "輸入", "原油", "LNG", "石炭"],
    sources: ["財務省 貿易統計（e-Stat）"],
    updated: "2026-06-11",
  },
  {
    slug: "jp-energy-import-trend",
    title: "原油は一極化、LNGは多様：日本のエネルギー調達 10年の二つの方向",
    lede: "2016→2025年、原油は中東依存が77%→94%へ「一極化」、LNGは米シェール参入で供給国が多様なまま（ただし露は8%で残存し脱ロシアは未達）。同じ輸入燃料でも10年の進む方向は逆だった。",
    tags: ["地政", "エネルギー安全保障", "輸入", "原油", "LNG", "中東依存", "脱ロシア"],
    sources: ["財務省 貿易統計（e-Stat）"],
    updated: "2026-06-12",
  },
  {
    slug: "fit-price-by-source",
    title: "FITで安くなったのは太陽光だけ：電源別 買取価格の14年",
    lede: "FIT買取価格は事業用太陽光が40円(2012)→9.9円(2026)へ4分の1に、陸上風力も22→14円。だが地熱40・木質バイオマス24・中小水力34は14年間据え置き。量産が効く電源だけが安くなった。",
    tags: ["制度", "FIT", "再エネ", "買取価格", "太陽光"],
    sources: ["METI なっとく（FIT買取価格）"],
    updated: "2026-06-13",
  },
  {
    slug: "power9-fuel-crisis-recovery",
    title: "電力9社、そろって沈みそろって浮上：燃料危機の傷と記録的回復",
    lede: "2022年度、燃料高と円安で大手電力9社のうち8社が経常赤字に。だが翌2023年度は9社すべて黒字に回復し関西電力は7,660億円。燃料価格×料金制度のラグが生む利益のV字を9社の経常利益で読む。",
    tags: ["企業IR", "電力会社", "財務", "経常利益", "燃料費", "火力"],
    sources: ["金融庁 EDINET"],
    updated: "2026-06-13",
  },
  {
    slug: "power9-revenue-vs-margin",
    title: "売上最大でも利益率は最低：電力9社の規模と収益性",
    lede: "大手電力9社のFY2024決算で、売上最大の東京電力HD(6.8兆円)の営業利益率は3.4%と9社中最低。一方 関西10.8%・北陸11.8%。規模と稼ぐ力は一致しない。",
    tags: ["企業IR", "電力会社", "財務", "営業利益率", "収益性", "火力"],
    sources: ["金融庁 EDINET"],
    updated: "2026-06-14",
  },
  {
    slug: "eu-emissions-by-country-trend",
    title: "EU各国の脱炭素20年：最も減らしたのは誰か",
    lede: "EU ETS の対象排出量を加盟国は2005年から軒並み削減。最大減はフランス(-58%)・英国(-57%)、最も鈍いのはオランダ(-14%)。同じEUでも脱炭素のペースは国で大きく違う。",
    tags: ["ESG", "国際", "EU ETS", "排出量", "脱炭素"],
    sources: ["EEA EU ETS Data Viewer"],
    updated: "2026-06-15",
  },
  {
    slug: "power9-total-assets",
    title: "電力9社の巨大設備：売上の2倍超、10年で2〜4割増えた総資産",
    lede: "電力会社は資本集約産業。大手9社の総資産は売上の1.9〜2.85倍、しかも10年で20〜42%増えた。最大は中国電力+42%、最小は東京HD+10%（福島負担で投資余力に制約）。",
    tags: ["企業IR", "電力会社", "財務", "総資産", "資本集約", "火力"],
    sources: ["金融庁 EDINET"],
    updated: "2026-06-16",
  },
  {
    slug: "fuel-crisis-2022",
    title: "2022エネルギー危機で最も暴れたのは石炭：輸入燃料の値動き",
    lede: "2022年のエネルギー危機。原油は2.4倍、LNGは2.2倍に上がったが、最も激しく動いたのは石炭——豪州石炭は2020年比5.7倍(指数567)に急騰しその後反落。電力損益V字の入力側を輸入燃料で読む。",
    tags: ["燃料", "石炭", "LNG", "原油", "エネルギー危機", "火力"],
    sources: ["World Bank Pink Sheet"],
    updated: "2026-06-16",
  },
];

export function getInsightBySlug(slug: string): Insight | undefined {
  return INSIGHTS.find((i) => i.slug === slug);
}

export function searchInsights(
  insights: Insight[],
  query: string | null | undefined,
): Insight[] {
  if (!query) return insights;
  const q = query.trim().toLowerCase();
  if (!q) return insights;
  return insights.filter((i) => {
    if (i.slug.toLowerCase().includes(q)) return true;
    if (i.title.toLowerCase().includes(q)) return true;
    if (i.lede.toLowerCase().includes(q)) return true;
    if (i.tags.some((t) => t.toLowerCase().includes(q))) return true;
    return false;
  });
}
